### ISSUE TITLE
Query is dropped on outgoing http requests

### ISSUE THREAD

**Issue by rylev** [fermyon/spin-python-sdk#101]
When making an outbund http request, they query string is dropped.

Here you can see how the `path_and_query` is set to just the path. 

https://github.com/fermyon/spin-python-sdk/blob/c2a2d8c1a013f5d67b2a36fa5014067bd2a9911f/src/spin_sdk/http/__init__.py#L178

I believe the fix is:

```python
path_and_query = parsed_url.path
if parsed_url.query:
     path_and_query += '?' + parsed_url.query
outgoing_request.set_path_with_query(path_and_query)
```

**Comment by dicej** [comment]
Good catch!  Your proposed fix looks reasonable to me.  Would you mind opening a PR?
