### ISSUE TITLE
CI: Auto-generate plugin manifest on tag push; PR to fermyon/spin-plugins

### ISSUE THREAD

**Issue by vdice** [fermyon/spin-python-sdk#31]
When a semver tag is pushed (eg v0.3.0), auto-generate the plugin manifest filled in with all of the necessary os/arch urls and digests and then create a PR in the https://github.com/fermyon/spin-plugins repo which:

- Renames the prior latest manifest according to its version eg `py2wasm.json` becomes `py2wasm@0.4.0.json`
- Adds the auto-generated plugin manifest as the new, latest manifest, eg `py2wasm.json`

**Comment by karthik2804** [comment]
This is not required any longer as the new python SDK does not depend on plugins.
