### ISSUE TITLE
does http_send() trigger cloudflare protections?

### ISSUE THREAD

**Issue by dejbug** [fermyon/spin-python-sdk#48]
I'm fetching the [Arts & Letters Daily](https://aldaily.com) front page but getting 403-ed when using `http_send`. It works fine though when using native Python and with curl (indicating that it's neither an IP nor a headlessness issue). It almost looks like Cloudflare's anti-bot protections are triggered with one and not the other for some reason.

Inspecting the network packets showed that `http_send` will [lowercase and reorder](https://github.com/fermyon/spin/blob/ced6f0e9a04631de351e0d137873be301d7e08bb/crates/outbound-http/src/lib.rs#L53) the headers, which [I was told](https://discord.com/channels/926888690310053918/950022897160839248/1130704753601548390) is how Rust's [HeaderMap](https://docs.rs/http/latest/http/header/index.html#deterministic-ordering) works. While this is [perfectly fine by the specs](https://www.rfc-editor.org/rfc/rfc2616#section-4.2) I was worried that it might be used to sanity-check the user-agent string I'm habitually spoofing. (Firefox for example will always send the host header first and in title-case.) Before turning to the discord chat this was my best guess at explaining why with some sites I've been getting different responses depending on whether I fetch natively or spinned but the friendly folks over at the discord server have quickly figured out that ordering and case apparently don't matter. (And indeed, it turns out that **any** user-agent string at all will work as long as one is specified.) Instead [I was pointed](https://discord.com/channels/926888690310053918/950022897160839248/1130728324981866646) to the phenomenon of [TLS fingerprinting](https://httptoolkit.com/blog/tls-fingerprinting-node-js/) as a more likely possibility.

Specifically:

```python
from urllib.request import urlopen, Request

def fetch():
	req = Request("https://aldaily.com", headers = { "user-agent": "X" })
	res = urlopen(req)
	return res.read().decode("utf8") if res.status == 200 else None
```

works fine, but

```python
from spin_http import http_send, Request

def fetch():
	req = Request("GET", "https://aldaily.com", { "user-agent": "X" }, None)
	res = http_send(req)
	return res.body.decode("utf8") if res.status == 200 else None
```

from the same IP would fail with `HttpError::DestinationNotAllowed`. One basically gets the same response as with a naked curl call:

```bash
curl 'https://www.aldaily.com'
```

By contrast, the simplest working curl call is:

```bash
curl 'https://www.aldaily.com' -H 'User-Agent: X'
```

**Comment by karthik2804** [comment]
Hey @dejbug, 

That error you are running into seems to be due to not setting a `allowed_http_hosts` value in your `spin.toml`. 

```
[[component]]
.
.
allowed_http_hosts = ["https://www.aldaily.com"]
```

Also, note that you need `https://www.aldaily.com` as `https://aldaily.com` has a permanent redirect.

reference: https://developer.fermyon.com/spin/writing-apps#granting-networking-permissions-to-components

**Comment by dejbug** [comment]
Hi @karthik2804 !

Hmm. My `spin.toml` looks like this (so far):

```
# ...

[[component]]
id = "ibtimes"
source = "ibtimes.wasm"
environment = { RATE = "3600" }
key_value_stores = ["default"]
allowed_http_hosts = [ "https://www.ibtimes.com" ]

[component.trigger]
route = "/ibtimes"

[component.build]
command = "spin py2wasm ibtimes -o ibtimes.wasm"
watch = ["ibtimes.py", "Store.py", "fetch.py", "abs.py", "Pipfile"]


[[component]]
id = "aldaily"
source = "aldaily.wasm"
environment = { RATE = "3600" }
key_value_stores = ["default"]
allowed_http_hosts = [ "https://www.aldaily.com" ]

[component.trigger]
route = "/aldaily"

[component.build]
command = "spin py2wasm aldaily -o aldaily.wasm"
watch = ["aldaily.py", "Store.py", "fetch.py", "Pipfile"]


[[component]]
id = "weforum"
source = "weforum.wasm"
environment = { RATE = "3600" }
key_value_stores = ["default"]
allowed_http_hosts = [ "https://www.weforum.org" ]

[component.trigger]
route = "/weforum"

[component.build]
command = "spin py2wasm weforum -o weforum.wasm"
watch = ["weforum.py", "Store.py", "fetch.py", "Pipfile"]
```

**Comment by karthik2804** [comment]
Hey @dejbug in your python code, can you change the request URL to be `https://www.aldaily.com`.

Alternatively in the `spin.toml` you can add `https://aldaily.com` in addition to the existing (i.e)

```
allowed_http_hosts = [ "https://aldaily.com", "https://www.aldaily.com" ]
```

**Comment by karthik2804** [comment]
This is the piece of code I am using and it seems to be returning the webpage properly 

```
from spin_http import Request, Response, http_send

def fetch():
        req = Request("GET", "https://www.aldaily.com", { "user-agent": "X" }, None)
        res = http_send(req)
        return res.body.decode("utf8") if res.status == 200 else None


def handle_request(request):
    print(fetch())
    return Response(200, {"content-type": "text/plain"})
```

and here is my `spin.toml`

```
spin_manifest_version = "1"
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""
name = "test-http"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "test-http"
source = "app.wasm"
allowed_http_hosts = ["https://www.aldaily.com"]
[component.trigger]
route = "/..."
[component.build]
command = "spin py2wasm app -o app.wasm"
watch = ["app.py", "Pipfile"]
```

**Comment by dejbug** [comment]
You're right @karthik2804 ! I've just tried it in a freshly spinned-up, single-component app like yours and it works as expected. At least this proves that it's not an issue with `http_send`. Now I need to figure out what is going wrong in my multi-component attempt.

Thanks a bunch! and please feel free to close this issue.

**Comment by dejbug** [comment]
Hmm... unless it's a compounded issue? Maybe `http_send()` in conjunction with my specific IP (I'm in Serbia right now, which seems to trigger some occasional Cloudflares while browsing normally)? Do you think this possible? Is there an easy way to test? Maybe with a VPN?

**Comment by dejbug** [comment]
Amazing.

When I use an agent string of `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0` I get the CAPTCHA. When I use an agent string of `X` I get the proper page. Both work with curl but the first one makes `http_send` fail. I hope I'm hallucinating, it's late.

**Comment by karthik2804** [comment]
I am not entirely sure what is going on there. I do not have any particularly good guesses either.

**Comment by karthik2804** [comment]
@dejbug I am closing this now but feel free to reopen if there are more questions.
