### ISSUE TITLE
Spin LLM support in Python

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin-python-sdk#50]
Following the release of the LLM apis in Spin, it would be great to also have support for those apis in the Python SDK. Ref: https://github.com/fermyon/spin/blob/main/wit/preview2/llm.wit

**Comment by benwilde** [comment]
Thanks @mikkelhegn!

**Comment by endocrimes** [comment]
partial support (inferencing sans embedding) is now in #51

**Comment by karthik2804** [comment]
This is now completed.
