### ISSUE TITLE
spin build failed  Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding

### ISSUE THREAD

**Issue by aamirmajeedkhan** [fermyon/spin-python-sdk#63]
Building component hello-python with `spin py2wasm app -o app.wasm`
Python path configuration:
  PYTHONHOME = '/python'
  PYTHONPATH = '/python:/0'
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = '/python/lib/python3.11'
  sys._base_executable = ''
  sys.base_prefix = '/python'
  sys.base_exec_prefix = '/python'
  sys.platlibdir = 'lib'
  sys.executable = ''
  sys.prefix = '/python'
  sys.exec_prefix = '/python'
  sys.path = [
    '/python',
    '/0',
    '/python/lib/python311.zip',
    '/python/lib/python3.11',
    '/python/lib/python3.11/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00000000 (most recent call first):
  <no Python frame>
Error: the `wizer.initialize` function trapped

Caused by:
    0: error while executing at wasm backtrace:
           0: 0x35351d - <unknown>!__wasi_proc_exit
           1: 0x34fc86 - <unknown>!_Exit
           2: 0x3547a5 - <unknown>!exit
           3: 0x1a3197 - <unknown>!fatal_error_exit
           4: 0x1a1849 - <unknown>!fatal_error
           5: 0x1a1473 - <unknown>!Py_ExitStatusException
           6: 0x1a142b - <unknown>!Py_InitializeEx
           7: 0x423bf - <unknown>!parking_lot::once::Once::call_once_force::{{closure}}::h75e202d36c0ea4bd
           8: 0x45b88 - <unknown>!parking_lot::once::Once::call_once_slow::h0caa9fca9f6946c8
           9: 0x427ce - <unknown>!pyo3::gil::prepare_freethreaded_python::h0c4a4fa53b21dcf7
          10: 0x101c9 - <unknown>!wizer.initialize
       note: using the `WASMTIME_BACKTRACE_DETAILS=1` environment variable may show more debugging information
    1: Exited with i32 exit status 1
Error: Couldn't create wasm from input
Error: Build command for component hello-python failed with status Exited(1)

**Comment by dicej** [comment]
Thanks for the report @aamirmajeedkhan.  I just tried to reproduce this using Spin v2.0.1 and `py2wasm` v0.3.2 on Linux/x86_64, but I wasn't able to.  I used the `hello_world` example in this repository, and it build and ran fine using `spin build -u`.  Would you please provide more detail, e.g. which platform you're using, Spin and `py2wasm` versions, and which example you're trying to run?

**Comment by dicej** [comment]
I don't think this issue is relevant anymore given that the SDK has been rebuilt from scratch using `componentize-py`.  Please feel free to reopen with further details if it comes up again using 2.0.0 or later.
