### ISSUE TITLE
Deprecate this project in favor of `componentize-py` and a new `spin-sdk` pip package

### ISSUE THREAD

**Issue by dicej** [fermyon/spin-python-sdk#64]
[componentize-py](https://github.com/bytecodealliance/componentize-py) is a more advanced and versatile solution to embedding Python code in Wasm than the `py2wasm` utility provided by this project.  Among other things, it supports arbitrary WIT worlds, native extensions, and typed binding generation.  See [this blog post](https://www.fermyon.com/blog/introducing-componentize-py) for details.

However, all the developer.fermyon.com docs point to this project, and it's not yet as easy to build Spin components with `componentize-py` due to the lack of pre-packaged, user-friendly bindings.  I'm proposing that we address both of those issues with the following steps:

1. Create and publish a PyPI package called `spin-sdk` which provides bindings to all the same Spin APIs as this project does, plus `wasi-http`.  This may include a mix of bindings generated directly from WIT files and some wrappers that make certain APIs easier to use in cases where the raw WIT bindings are complicated and/or not idiomatic.
2. Update the developer.fermyon.com docs to use `componentize-py` and `spin-sdk`.
3. Archive this project, updating the README.md to point to the new projects.

**Comment by karthik2804** [comment]
I think we can close this now as we have moved the newer SDK into the repo.
