### ISSUE TITLE
Template is Spin manifest version 1

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin-python-sdk#75]
The template in this idrectory is using the Spin manifest version 1, so the instructinos over here are failing: https://developer.fermyon.com/spin/v2/python-components

**Comment by itowlson** [comment]
see also https://discordapp.com/channels/926888690310053918/950022897160839248/1209213581023776818

**Comment by karthik2804** [comment]
This should be fixed now as the template has been updated and tagged.
